//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.13 at 03:01:19 рм EEST 
//


package eu.faredge.eg.analytics.commons.models.eaprocessorspec;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.faredge.eg.analytics.commons.models.eaprocessorspec package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProcessorType_QNAME = new QName("http://www.faredge.eu/ea/processor", "processorType");
    private final static QName _ProcessorLocation_QNAME = new QName("http://www.faredge.eu/ea/processor", "processorLocation");
    private final static QName _ProcessorName_QNAME = new QName("http://www.faredge.eu/ea/processor", "processorName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.faredge.eg.analytics.commons.models.eaprocessorspec
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessorConfigs.InputStream }
     * 
     */
    public ProcessorConfigs.InputStream createProcessorConfigsInputStream() {
        return new ProcessorConfigs.InputStream();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link ProcessorConfigs }
     * 
     */
    public ProcessorConfigs createProcessorConfigs() {
        return new ProcessorConfigs();
    }

    /**
     * Create an instance of {@link EaProcessorSpec }
     * 
     */
    public EaProcessorSpec createEaProcessorSpec() {
        return new EaProcessorSpec();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.faredge.eu/ea/processor", name = "processorType")
    public JAXBElement<String> createProcessorType(String value) {
        return new JAXBElement<String>(_ProcessorType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.faredge.eu/ea/processor", name = "processorLocation")
    public JAXBElement<String> createProcessorLocation(String value) {
        return new JAXBElement<String>(_ProcessorLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.faredge.eu/ea/processor", name = "processorName")
    public JAXBElement<String> createProcessorName(String value) {
        return new JAXBElement<String>(_ProcessorName_QNAME, String.class, null, value);
    }

}
