//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.13 at 03:21:40 μμ EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.faredge.eu/ea/orchestrator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.faredge.eg.analytics.commons.models.easpec;
